name: 'Notify Telegram'
description: 'Get build notification to Telegram messenger'
author: 'yanzay'
inputs: 
  chat:
    description: 'Chat to send: chat id or @channel_name'
    required: true
  token:
    description: 'Telegram Bot token'
    required: true
  message:
    description: 'send message text'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: 'pre.sh'
  entrypoint: 'entrypoint.sh'
  post-entrypoint: 'post.sh'
branding:
  icon: 'send'
  color: 'blue'
