name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Build go
      run: CGO_ENABLED=0 go build -v -o notify-telegram .
    
    - name: Build docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com/${{ github.repository }}
#     - name: Build
#       run: exit 1
      
#     - uses: yanzay/notify-telegram@master
#       if: always()
#       with:
#         chat: ${{ secrets.chat }}
#         token: ${{ secrets.token }}
#         status: ${{ job.status }}
